# 存储参数-PPO
task: MiniGrid-LavaCrossingS11N5-v0
algo_name: PPO_ACObs7_CNN
resume_id: null
logdir: log
device: cuda
logger: wandb

# net & env参数-AsyAC
obs_1: 7
obs_2: 11

# 训练参数-PPO
stack_num: 1
epoch: 50
step_per_epoch: 4.e+4
lr: 1.e-4
training_num: 16
test_num: 16
step_per_collect: 2000
repeat_per_collect: 10
buffer_size: 1.e+6
batch_size: 128
gamma: 0.99
render: 0
reward_threshold: 1
seed: 1
hidden_sizes: [128, 128]

# 算法参数-PPO
vf_coef: 0.25
ent_coef: 0.01 # lambda_entropy 
eps_clip: 0.2   # clip epsilon
max_grad_norm: 0.5
gae_lambda: 0.95
dual_clip: null
value_clip: 1
norm_adv: 1
recompute_adv: 0
rew_norm: False
alpha: 0.6
beta: 0.4


