# 存储参数-DQN
task: MiniGrid-SimpleCrossingS11N5-v0
algo_name: DQN_FullObs11_CNN
resume_id: null
logdir: log
device: cuda
logger: wandb

# 训练参数-DQN
stack_num: 1
epoch: 50
step_per_epoch: 4.e+4
lr: 1.e-4
training_num: 16
test_num: 16
step_per_collect: 16
n_step: 3
update_per_step: 0.1
batch_size: 128
gamma: 0.99
render: 0
reward_threshold: 1
seed: 1
hidden_sizes: [128, 128]

# 算法参数-DQN
eps_test: 0.05
eps_train: 0.3
buffer_size: 1.e+6
target_update_freq: 320
alpha: 0.6
beta: 0.4


