_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "9":
                "2": tianshou
            "12": 0.19.8
            "13": linux-x86_64
